#!/bin/bash

case "${HOSTNAME}" in
vm*)
    make clean && make && make install && make installcheck REGRESS_OPTS="--port=$PGPORT"
    ;;
*)
    sudo eselect postgresql set 9.2
    sudo make clean && sudo make && sudo make install && sudo make installcheck
    sudo /etc/init.d/postgresql-9.2 stop
    sudo /etc/init.d/postgresql-9.3 start
    sudo eselect postgresql set 9.3
    sudo make clean && sudo make && sudo make install && sudo make installcheck
    sudo /etc/init.d/postgresql-9.3 stop
    sudo /etc/init.d/postgresql-9.2 start
    sudo eselect postgresql set 9.2
    ;;
esac
